### ISSUE TITLE
possibilidade incluir link inteiro ao invez de so id do video.

### ISSUE THREAD

**Issue by rafaelluciodeveloper** [gabrielfroes/youtube-chapter-extractor#1]
colocar na extract uma opcao de verificar o value
e remover 'https://www.youtube.com/watch?v=' e capturar so o link 

algo como.

`value = value.replace('https://www.youtube.com/watch?v=',"");
`

**Comment by guicaires** [comment]
Concordo, para o usuário é bem mais rápido e intuitivo pegar o link inteiro e jogar no input.

**Comment by gabrielfroes** [comment]
Tem razão pessoal! Vamos adicionar essa possibilidade no vídeo que iremos refatorar o front-end para consumir a API do serviço.

**Comment by gabrielfroes** [comment]
Incluímos nesse último PR! Muito obrigado pela sugestão.
